# ####
#' De-seasonalize variable
#'
#' Use GAM analysis to de-seasonalize variable. Relies on mgcv::gam to perform general additive model.
#' 
#' @param df data frame
#' @param var  variable
#' @param deSeasonalizeModel which gam formula is used. Default: 'gam2'.
#' @param analySpec analytical specifications
#' @param gamTable gam table setting (set to FALSE to turn off table output)
#' @param gamPlot gam plot setting (set to FALSE to turn off plotting)
#' @param flow.detrended data generated by detrended.flow.  Default = NA.
#' @param salinity.detrended data generated by detrended.flow.  Default = NA.
#'
#' @return Returns a vector with results
#' @export
#'
# ####

deSeasonalize <- function(df, var
                          , deSeasonalizeModel = 'gam2'
                          , analySpec = analySpec
                          , gamTable = FALSE
                          , gamPlot = FALSE
                          , gamDiffModel = NA
                          , flow.detrended = NA
                          , salinity.detrended = NA) {
  
  # error trap: all variables present?
  {
    vars <- c(var, "year", "doy", "dyear", "month", "nummon") 
    if (sum(vars %in% names(df)) <6) {
      warning(paste(" Variables not found: ", paste(vars[!vars %in% names(df)], collapse = ', ')))
      return(NA)
    }
  }
  
  # error trap: is  variable of qw type
  if (!class(df[,var])=='qw') {
    warning(paste0("Variable not of qw class: ",var))
    return(NA)
  }
  
  # error trap: evaluate gam model choice
  if (class(deSeasonalizeModel)=="list" ) {
    print(paste0("User specified model for deseasonalizing selected"))
    analySpec$gamModels <- deSeasonalizeModel
  }
  
  # set up deseasonalizing model
  if (class(deSeasonalizeModel)=="character") {
    if (deSeasonalizeModel %in% c('gam2', 'gam4')) {
      if (deSeasonalizeModel == 'gam2') {
        analySpec$gamModels   <- list(
          list(option=2, name= "Non-linear trend with Seas+Int",
               model= paste0(" ~ cyear + s(cyear, k=gamK1) + s(doy,bs='cc')",
                             " + ti(cyear,doy,bs=c('tp','cc'))"), 
               deriv=TRUE, gamK1=c(10,2/3), gamK2=c(NA,NA)))
      } else if (deSeasonalizeModel == 'gam4') {
        analySpec$gamModels   <- list(
          list(option=4, name= "Non-linear trend with Seas+Int. & Hydro Adj",
               model= paste0("~ cyear + s(cyear, k=gamK1) + s(doy,bs='cc')",
                             " + ti(cyear,doy,bs=c('tp','cc'))",
                             " + s(flw_sal,k=gamK2)",
                             " + ti(flw_sal,doy,bs=c('tp','cc'))",
                             " + ti(flw_sal, cyear,bs=c('tp' ,'tp'))",
                             " + ti(flw_sal,doy,cyear, bs=c('tp','cc','tp'))"),
               deriv=TRUE, gamK1=c(10,1/3), gamK2=c(10,2/3)))
      }
    } else {
      warning(paste0("Valid model for deseasonalizing is not selected: ",deSeasonalizeModel))
      return(NA)
    }
  }
  
  # print selected gam model
  if(gamTable | !gamPlot==FALSE) {  # only show header if tables or figures are outputted
    .H4(paste("Model: ",analySpec$gamModels[[1]]$model))
  }
  
  print(analySpec$gamModels[[1]]$model)
  
  # down select station list and layer list
  analySpec$stationList <- analySpec$stationList[analySpec$stationList$stations %in% unique(df$station),]
  analySpec$layerList <- analySpec$layerList[analySpec$layerList$layers %in% unique(df$layer),]
  
  stations  <- analySpec$stationList$stations
  layers    <- analySpec$layerList$layers
  
  for (layer in layers) { 
    for (stat in stations) { 
      # layer="S"; stat="CB5.4"
      if(gamTable | !gamPlot==FALSE) {  # only show header if tables or figures are outputted
        .H4(paste("Processing: ",stat,"/",layer))
      }
      gamResult <- gamTest(df, var, stat, layer, analySpec
                           , gamTable = gamTable
                           , gamPlot = gamPlot
                           , gamDiffModel = NA
                           , flow.detrended = flow.detrended
                           , salinity.detrended = salinity.detrended)
      if (!is.na(gamResult[1])) { 
        residuals <- eval(parse(text = paste0("gamResult$gamOutput"
                                              , analySpec$gamModels[[1]]$option
                                              ,"$gamRslt$residuals")))
        var.res0 <- cbind(gamResult$data[,c("station","date","layer")],residuals)
        if (!exists("var.res1")) {
          var.res1 <- var.res0
        } else { 
          var.res1 <- rbind(var.res1, var.res0)
        }
        # df[df$station==stat & df$layer==layer & !is.na(df[,var]), "residuals"] <- var.res
      }  
    }
  }
  
  df <- merge(df,var.res1, by=c("station","date","layer"), all.x=TRUE)
  
  return(df[,"residuals"])
}

# plot(var.res1$residuals ~ var.res1$date)
# boxplot(var.res1$residuals ~ var.res1$station)

